name: Golang CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
  - cron: '15 3 * * 0'

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Fetch vendor
      run: go mod vendor

    - name: Test and build
      run: go run github.com/rebuy-de/rebuy-go-sdk/v5/cmd/buildutil
